name: ci

on: [push, pull_request]

jobs:
  check:
    name: check ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Format
        run: deno fmt --check
